spring.application.name=financialInstrumentsSubscriptionsManager

spring.output.ansi.enabled=ALWAYS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/stock_trading_financial_instrument_subscription_manager
spring.datasource.username=postgres
spring.datasource.password=

spring.task.scheduling.pool.size=10

logging.level.org.springframework.web: DEBUG
logging.level.com.piotrgrochowiecki.financialInstrumentsSubscriptionsManager.FinancialInstrumentsSubscriptionsManagerApplication=DEBUG

dataloader.lastCheckInHealthThreshold.milisec=10000
dataloader.recommendedNumberOfFinancialInstruments=5