spring.application.name=financialInstrumentsSubscriptionsManager

spring.output.ansi.enabled=ALWAYS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/stock_trading_financial_instrument_subscription_manager
spring.datasource.username=postgres
spring.datasource.password=

spring.task.scheduling.pool.size=10

logging.level.com=DEBUG
#logging.level.org.springframework.web:DEBUG

dataLoader.activeThreshold.millisecond=10000
dataLoader.recommendedNumberOfFinancialInstrumentsPerDataLoader=5
dataLoader.readyForHandlingThreshold.millisecond=15000
dataLoader.numberOfDataLoadersHandledByManagerInOneReassignmentCycle=2

financialInstrument.recommendedNumberOfFinancialInstrumentsUnassignedToAnyDataLoaderToBeHandledBySingleInstance=5